### ISSUE TITLE
Issue while scan smb 1 is activated 

### ISSUE THREAD

**Issue by wolfyy59** [d4t4s3c/Win7Blue#2]
Exception: a bytes-like object is required, not 'str'

**Comment by d4t4s3c** [comment]
> Exception: a bytes-like object is required, not 'str'

Hello friend, can you send me a screenshot? and give me more details of the error. thanks for informing

**Comment by wolfyy59** [comment]
> > Exception: a bytes-like object is required, not 'str'
> 
> Hello friend, can you send me a screenshot? and give me more details of the error. thanks for informing

I use python2 now it says it's not vulnerable even port 445 is opened its normal?

**Comment by wolfyy59** [comment]
![Uploading Screenshot_20221124-202839.png…]()

**Comment by d4t4s3c** [comment]
I can't see your image

**Comment by d4t4s3c** [comment]
I have solved it by changing the version of python to python2

![imagen](https://user-images.githubusercontent.com/50043005/203856337-43cb2916-6fd9-4adc-91ef-5d7c29d79692.png)

![imagen](https://user-images.githubusercontent.com/50043005/203856437-1dce5c52-b643-41b7-a575-22d09938d27c.png)

![imagen](https://user-images.githubusercontent.com/50043005/203856602-2967a114-9cbb-4898-a526-88cc3bae0587.png)

https://github.com/d4t4s3c/Win7Blue/commit/b6f43cb06245df5628046fab65cc9a41f52b5354

**Comment by d4t4s3c** [comment]
if you clone the repository again it should work without problem

**Comment by wolfyy59** [comment]
Thanks
